ch14/students03/config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :sessions

  resources :users
  resources :courses do
  	member do
  		get :roll
  	end
  end

  resources :students do
		resources :awards

		member do
			get :courses
			post :course_add
			post :course_remove
		end
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'students#index'
end

ch14/students03/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ch14/students03/app/models/award.rb
class Award < ApplicationRecord

	belongs_to :student
	validates_associated :student
end

ch14/students03/app/models/course.rb
class Course < ApplicationRecord
	has_and_belongs_to_many :students
end

ch14/students03/app/models/student.rb
class Student < ApplicationRecord

	has_many :awards, dependent: :destroy
	has_and_belongs_to_many :courses

	def name
		given_name + " " + family_name
	end

	def enrolled_in?(course)
			self.courses.include?(course)
	end

	def unenrolled_courses
			Course.all - self.courses
	end
end

ch14/students03/app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

ch14/students03/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	private
		def current_user
		  @current_user ||= User.find(session[:user_id]) if session[:user_id]
		end
	helper_method :current_user

		def authorize
		  redirect_to login_url, alert: "Not authorized" if current_user.nil?
		end

		def is_admin
		  redirect_to students_path, alert: "Not authorized" if current_user.nil? or !current_user.admin
		end
end

ch14/students03/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # user = User.where(email: params[:email]).first
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.notice = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

ch14/students03/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
	  @user = User.new
	end

	def create
	  @user = User.new(user_params)
	  if @user.save
	    session[:user_id] = @user.id
	    redirect_to root_url, notice: "Thank you for signing up!"
	  else
	    render "new"
	  end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_user
	  @user = User.find(params[:id])
	end
	# Never trust parameters from the scary internet, only allow the white list through.
	def user_params
	  params.require(:user).permit(:email, :password, :password_confirmation, :admin)
	end
end

ch14/students03/app/views/students/_form.html.erb
<%= form_for(student) do |f| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :given_name %><br>
    <%= f.text_field :given_name %>
  </div>

  <div class="field">
    <%= f.label :middle_name %><br>
    <%= f.text_field :middle_name %>
  </div>

  <div class="field">
    <%= f.label :family_name %><br>
    <%= f.text_field :family_name %>
  </div>

  <div class="field">
    <%= f.label :date_of_birth, "DOB" %><br>
    <%= f.date_select :date_of_birth, :start_year => 1930, :end_year => 1970 %>
  </div>

  <div class="field">
    <%= f.label :grade_point_average, "GPA" %><br>
    <%= f.text_field :grade_point_average %>
  </div>

  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ch14/students03/app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Given name</th>
      <th>Middle name</th>
      <th>Family name</th>
      <th>DOB</th>
      <th>GPA</th>
      <th>Start date</th>
      <th>Courses</th>
      <th>Awards</th>
      <th colspan="4"></th>
    </tr>
  </thead>

<tbody>
    <% @students.each do |student| %>
    <tr>
        <td><%= student.given_name %></td>
        <td><%= student.middle_name %></td>
        <td><%= student.family_name %></td>
        <td><%= student.date_of_birth %></td>
        <td><%= student.grade_point_average %></td>
        <td><%= student.start_date %></td>
        <td><%= student.courses.count %></td>
        <td><%= student.awards.count %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Awards', student_awards_path(student) %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Edit', edit_student_path(student) %></td>
          <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
    </tr>
    <% end %>
</tbody>
</table>
<br>
<% if current_user.admin? %>
  <%= link_to 'New Student', new_student_path %>
<% end %>